### ISSUE TITLE
一点点建议

### ISSUE THREAD

**Issue by maplewei** [dotnet-campus/dotnetCampus.FileDownloader#13]
最近，我仔细看了dotnetCampus.FileDownloader的项目，受益匪浅。我准备着手改造我之前写的下载程序，不过，关于分块的判断 是否通过请求头，判断是否有Accept-Ranges字段来判断好一些呢？如果有机会，我也想推送一些PR。

**Comment by lindexi** [comment]
@maplewei 十分欢迎

**Comment by lindexi** [comment]
其实不使用通过请求头是因为基本上 Ranges 是成为标准本身，因此通过这个判断对逗比服务器支持很弱，所以就采用下载后半部分的方法
