### ISSUE TITLE
建议说明丰富下独立运行程序的介绍

### ISSUE THREAD

**Issue by Jiuyong** [dotnet-campus/dotnetCampus.FileDownloader#18]
比如，说明里面加入运行界面的截图。

**Comment by lindexi** [comment]
@Jiuyong 感谢，开干

但是本来这个项目其实是作为库来使用的哈，而不是作为应用的，所以运行界面太丑也许会降低小伙伴的感觉

**Comment by lindexi** [comment]
这是当前的界面

![图片](https://user-images.githubusercontent.com/16054566/92109354-7274b400-ee1b-11ea-8fee-eb6eab660a56.png)

**Comment by lindexi** [comment]
加入 https://gitee.com/aduskin/AduDownload 开源库的界面支持

**Comment by lindexi** [comment]
![](https://github.com/dotnet-campus/dotnetCampus.FileDownloader/raw/68733230864081730a33abf6d41bb9dbfd277e0c/docs/images/AduDownload_with_FileDownloader_1.0.1.png)

**Comment by lindexi** [comment]
@ Jiuyong  现在首页更新了
