### ISSUE TITLE
文件下载初体验

### ISSUE THREAD

**Issue by maplewei** [dotnet-campus/dotnetCampus.FileDownloader#5]
1.我测试了下载一个100M的文件，发现，速度没有占满我的网速，大概在1M多每秒，希望可以根据用户的网速来提速。
2.我测试了在网络不稳定的情况下，没有断点续传功能，如果限速大概10几秒后，程序就不会再下载内容。

**Comment by lindexi** [comment]
@maplewei 能否提供你的下载地址给我测试？是否对方不支持断点续传

**Comment by maplewei** [comment]
https://img.3d66.com/ku/liuyunkuSetup.exe，这个是下载链接。文件是支持分块的。我可以说一下，我的测试步骤。首先指定下载地址后，我会不定时的使用网络限制软件把下载速度控制在1-500K之间，来回切换。如果设置为1K在几秒后，程序就不再走了。

**Comment by lindexi** [comment]
@maplewei  大概知道原因是，是网络在等待超时，但是等待时间好像有点久

**Comment by maplewei** [comment]
这种情况在生产环境中，是存在的，有的用户的网络质量很差，而且还会时不时的丢包，如果保证下载正常，需要在网络异常时，适当等待后，再次请求连接。直到文件下载完成。

**Comment by lindexi** [comment]
@maplewei  还没优化到这一步，暂时的功能是在非弱网环境下的压榨网络下载速度

后续将会支持弱网环境

**Comment by lindexi** [comment]
@maplewei 大佬，现在我加了弱网的支持了，但是能支持多弱的网，我还没测试

**Comment by maplewei** [comment]
@lindexi 大佬，我拉取之后又测试了一下。
![down](https://user-images.githubusercontent.com/13778095/93039408-fb8cb600-f679-11ea-8713-95cf519d3bd6.png)
结果，在最后完成的时候没有走到结束。不过，强行结束后，文件是可以使用的。其实，这段时间我一直在修改测试，我也加入了一些修复，不过一直不也推送。我不知道我修复的是否合理，还请大佬指点。
1.增加了定时巡检，如果长时间线程一直处于读取状态，但没有返回错误的，重新开始（原因是有时候会卡住，不知道为什么只好通过这个笨办法）
2.增加调速功能（就是启动的线程数量根据网速的快慢来调节，之前是try了之后，一直重复。不知道这样是否更好，或者可以节约最大连接数量的问题）
3.修改RandomFileWriterWithOrderFirst这个函数的连续合并块的逻辑改为KeyValue的形式，理想可以更快索引。不过，测试的数据还不太够。
综上，一直没有推送，怕会影响整体的代码质量。也望大佬指点一下，我再推送

**Comment by lindexi** [comment]
@maplewei  欢迎贡献代码，推荐分为小点推送哈

如果长时间线程一直处于读取状态，这个问题在 https://github.com/dotnet-campus/dotnetCampus.FileDownloader/pull/19 应该修复了，加了配置最长时间，默认是 10 秒

第二个点非常好，但是算法应该会比较复杂

第三个修改RandomFileWriterWithOrderFirst这个函数的连续合并块的逻辑改为KeyValue的形式，其实我没有看懂是如何实现哈
